# Pandas and Matplotlib Homework

In [1]:
#load the libraries using the normal convention
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
##prevent plotting errors
%matplotlib inline

/anaconda3/envs/itp_2018/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/envs/itp_2018/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
#Load our excel files of interest into pandas
NHL_Goalies = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheetname=0) 
GAA_ = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheetname='5vs5')

/anaconda3/envs/itp_2018/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)

#Appendix:
 1. DF = Pandas DataFrame
 2. NHL_Goalies DF = NHL_Goalies 
 3. GAA_ DF = GAA_

### Q1A) Create a new DF (*called NHL_Ones*) by:
#### Filtering the correct DF for Goalies that played 1 game <font color='red'> (GP = Games played)</font>

Notes: How would you find the 'GP' column in these files? Review from Pandas Lecture

In [3]:
# Answer 1A:

# find GP column in df, defining it as a variable here to use in next step
GP = NHL_Goalies.GP

# create new df, list players only when GP is equal to 1
NHL_Ones = NHL_Goalies[GP == 1]

# NHL_Ones
# NHL_Ones.GP

 ## Q1B) 
 #### A. Find the value of the minimum Salary for the entire dataset 
 #### B. Replace the missing values from the NHL_Ones DF with this
 #### C. Create a new DF after replacement by **adding** a column called  "Adjusted_Salary"
 #### D. I would like to only see the old "Salary" column and the "Adjusted Salary" column from the new Dataframe

#### Notes:
1. Note where the minimum Salary value is coming & where you are going to assign it to
2. Review notes from pandas **replacement**
3. Look up Numpy definition for null
4. Look up Pandas **Series** Naming 
5. Review concat function in Pandas
6. Review how to slice columns

In [4]:
# Answer 1B:
# A. Find the value of the minimum Salary for the entire dataset

Minimum_Salary = NHL_Goalies.Salary.min()

print('Minimum Salary: $',Minimum_Salary)

Minimum Salary: $ 575000.0

In [5]:
# Answer 1B:
# B. Replace the missing values from the NHL_Ones DF with this

NHL_Ones = NHL_Ones.replace('NaN', np.nan)
Adjusted_Salaries = NHL_Ones.Salary.replace(np.nan, Minimum_Salary)


print('Adjusted Salaries','\n', Adjusted_Salaries)

Adjusted Salaries
 1     575000.0
13    575000.0
14    575000.0
16    708750.0
22    780000.0
27    650000.0
29    925000.0
32    575000.0
42    575000.0
50    673334.0
67    575000.0
80    575000.0
87    832500.0
89    575000.0
90    892500.0
Name: Salary, dtype: float64

In [6]:
# Answer 1B: 
# C. Create a new DF after replacement by adding a column called "Adjusted_Salary"

NHL_Ones['Adjusted_Salary'] = Adjusted_Salaries

# NHL_Ones

In [7]:
# Answer 1B: 
# D. I would like to only see the old "Salary" column and the "Adjusted Salary" column from the new Dataframe

Salary_vs_Adjusted_Salary = pd.concat([NHL_Ones.Salary, NHL_Ones.Adjusted_Salary], axis=1)
Salary_vs_Adjusted_Salary

      Salary  Adjusted_Salary
1        NaN         575000.0
13       NaN         575000.0
14  575000.0         575000.0
16  708750.0         708750.0
22  780000.0         780000.0
27  650000.0         650000.0
29  925000.0         925000.0
32       NaN         575000.0
42  575000.0         575000.0
50  673334.0         673334.0
67       NaN         575000.0
80       NaN         575000.0
87  832500.0         832500.0
89       NaN         575000.0
90  892500.0         892500.0

### Q2) A. Subset the NHL goalies data to include Goalies that played in more than 25 games AND have a GAA lower than 3.00 and store the New DF as 'workhorse'

Notes: 
1. Review notes from Pandas Lecture on creating masks
2. Internet search for Multiple Boolean indexing on multiple columns in a Pandas DataFrame

In [8]:
# Answer 2:

GP = NHL_Goalies.GP
GAA = NHL_Goalies.GAA

Workhorse = NHL_Goalies[(GP > 25) & (GAA < 3.00)] 
 
# Workhorse
Workhorse_GP_GAA = pd.concat([Workhorse.GP, Workhorse.GAA], axis=1)
Workhorse_GP_GAA

    GP       GAA
0   61  2.422245
2   66  2.668889
3   40  2.279830
5   39  2.498516
9   39  2.537550
10  63  2.055534
12  60  2.176366
15  41  2.478041
18  55  2.550151
19  32  2.380694
23  65  2.251197
24  49  2.552369
28  52  2.216686
30  51  2.687252
34  28  2.802894
37  56  2.887738
38  63  2.070558
39  26  2.104937
40  28  2.916566
41  30  2.385114
43  36  2.592887
44  65  2.399779
46  26  2.642127
51  59  2.678047
52  59  2.851612
55  57  2.740374
56  40  2.682064
57  26  2.625326
59  58  2.660781
63  54  2.802123
66  49  2.407983
68  28  2.816006
70  26  2.668014
73  50  2.978442
74  62  2.232929
76  30  2.262984
77  65  2.233999
78  43  2.529486
79  61  2.421672
82  60  2.816144
84  55  2.923051
88  73  2.389381
92  50  2.606607
93  61  2.686629

### Q3. Create 2 python functions that: 
<br> </br>
#### A. Creates/*Returns* a new DataFrame that displays the number of missing values in every column. 
#### This new DataFrame has one new column named "Missing" with the sum of the missing values from the columns

### Notes 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
** One Proposed method:**
1. Create a pandas series object from the sum of the nulls in every column (review class notes)
2. Convert the series object to a DataFrame and pass the list of column names from the input DataFrame as the index. (read Pandas Help online)
3. During the conversion of the series object to a DataFrame pass a columns argument to create a name for the new Output DataFrame's Column.

### Expected Output:
<img src='Missing_cols_expectedoutput.png'>

In [9]:
# Answer 3A: CODE HERE; Please comment each part
# 1. Create a pandas series object from the sum of the nulls in every column (review class notes)
# 2. Convert the series object to a DataFrame and pass the list of column names from the input DataFrame as the index. (read Pandas Help online)
# 3. During the conversion of the series object to a DataFrame pass a columns argument to create a name for the new Output DataFrame's Column.


def Missing_Cols(df):
    na_sum_series = pd.Series(df.isnull().sum()) # new pd series: sum of nulls in each column
    Missing_Cols = pd.DataFrame(na_sum_series, columns = ['Missing']) # convert series into df, new col named Missing
    return Missing_Cols # return final df

Missing_Cols(NHL_Goalies)

            Missing
Last Name         0
First Name        0
Team              0
DOB               0
Birth City        0
S/P              34
Cntry             0
Nat               0
Ht                0
Wt                0
Sh                0
Dft Yr           17
Rd               17
Ovrl             17
GP                0
GS                0
GR                0
W                 0
L                 0
T                 0
OTL               0
SA                0
SV                0
GA                0
SV%               0
GAA               0
GSAA              0
MIN               0
SO                0
G                 0
...             ...
xGSAA             0
ZS%               0
OZS               0
DZS               0
NZS               0
CF                0
FF                0
SF                0
xGF               0
GF                0
RebF              0
RushF             0
SOS               0
SOG               0
SO SV%            0
SOW               0
SOL               0
NMC              77
Status            6
Salary            6
Cap Hit           6
Pace              0
1st              23
2nd              23
3rd              23
Star             23
GPS               0
Ginj             58
Injuries         58
CHIP              0

[111 rows x 1 columns]

#### B. Creates a new *column* called 'missing_values' in the input DF that sums the missing values in each row.

### Notes: 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
Review the Column creation method in lecture and the axis arguments needed

### Expected Output:
<img src= 'missingrows_expectedoutput.png'>

In [11]:
#Answer 3B here; Please comment each part
def Missing_Values(df):
    na_sum_series = pd.Series(df.isnull().sum(axis = 1)) # new pd series: sum of nulls in each row
    na_sum_series = pd.DataFrame(na_sum_series, columns = ['Missing_Values']) # convert series into df, new col named Missing_Values
    Missing_Values = pd.concat([df, na_sum_series], axis=1) # concatenate old df with new one
    return Missing_Values # return final df

Missing_Values(NHL_Goalies)

,Last Name,First Name,Team,DOB,Birth City,S/P,Cntry,Nat,Ht,Wt,...,Pace,1st,2nd,3rd,Star,GPS,Ginj,Injuries,CHIP,Missing_Values
0,Allen,Jake,STL,1990-08-07,Fredericton,NB,CAN,CAN,74,203,...,104.033662,9.0,7.0,6.0,22.0,9.8,NaN,NaN,,3
1,Alves,Jorge,CAR,1979-01-30,Boston,MA,USA,USA,69,185,...,0.000000,NaN,NaN,NaN,NaN,0.0,NaN,NaN,,18
2,Andersen,Frederik,TOR,1989-10-02,Herning,NaN,DNK,DNK,76,230,...,118.931391,9.0,6.0,6.0,21.0,13.1,2.0,Upper body,121951,2
3,Anderson,Craig,OTT,1981-05-21,Park Ridge,IL,USA,USA,74,187,...,114.858819,8.0,2.0,5.0,15.0,9.2,2.0,Lower body,102439,1
4,Bachman,Richard,VAN,1987-07-25,Salt Lake City,UT,USA,USA,70,183,...,113.421038,1.0,0.0,1.0,2.0,1.1,NaN,NaN,,3
5,Bernier,Jonathan,ANA,1988-08-07,Laval,QC,CAN,CAN,72,184,...,113.938340,5.0,0.0,2.0,7.0,6.0,3.0,Upper body,151829,1
6,Berra,Reto,FLA,1987-01-03,Bulach,NaN,CHE,CHE,76,210,...,108.457976,NaN,NaN,NaN,NaN,0.2,NaN,NaN,,8
7,Berube,Jean-Francois,NYI,1991-07-13,Repentigny,QC,CAN,CAN,73,177,...,114.005505,0.0,1.0,1.0,2.0,0.8,NaN,NaN,,3
8,Bibeau,Antoine,TOR,1994-05-01,Victoriaville,QC,CAN,CAN,75,210,...,130.294240,NaN,NaN,NaN,NaN,0.4,NaN,NaN,,7
9,Bishop,Ben,"TBL, LAK",1986-11-21,Denver,CO,USA,USA,79,216,...,108.466747,0.0,1.0,5.0,6.0,5.7,9.0,Lower body,653049,0
10,Bobrovsky,Sergei,CBJ,1988-09-20,Novokuznetsk,NaN,RUS,RUS,74,182,...,109.525950,17.0,6.0,6.0,29.0,14.9,2.0,Illness,181098,4
11,Brossoit,Laurent,EDM,1993-03-23,Port Alberni,BC,CAN,CAN,75,204,...,110.633178,1.0,1.0,0.0,2.0,1.2,NaN,NaN,,3
12,Budaj,Peter,"LAK, TBL",1982-09-18,Banská Bystrica,NaN,SVK,SVK,73,196,...,108.110995,4.0,7.0,4.0,15.0,8.6,NaN,NaN,,4
13,Campbell,Jack,LAK,1992-01-09,Port Huron,MI,USA,USA,74,197,...,96.000000,NaN,NaN,NaN,NaN,0.1,NaN,NaN,,11
14,Comrie,Eric,WPG,1995-07-06,Edmonton,AB,CAN,CAN,73,175,...,124.451939,NaN,NaN,NaN,NaN,0.2,NaN,NaN,,7
15,Condon,Mike,"PIT, OTT",1990-04-27,Holliston,MA,USA,USA,74,197,...,112.079733,9.0,1.0,4.0,14.0,6.8,NaN,NaN,,6
16,Copley,Pheonix,STL,1992-01-18,North Pole,AK,USA,USA,76,196,...,104.864253,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,,10
17,Coreau,Jared,DET,1991-11-05,Perth,ON,CAN,CAN,78,220,...,108.674473,1.0,1.0,1.0,3.0,1.0,NaN,NaN,,6
18,Crawford,Corey,CHI,1984-12-31,Montreal,QC,CAN,CAN,74,216,...,112.428393,8.0,5.0,0.0,13.0,11.0,11.0,"Appendectomy, Illness",804878,0
19,Darling,Scott,CHI,1988-12-22,Newport News,VA,USA,USA,78,232,...,109.476386,5.0,5.0,5.0,15.0,6.2,5.0,Upper body,35823.2,1
20,Dell,Aaron,SJS,1989-05-04,Airdrie,AB,CAN,CAN,72,205,...,114.105623,3.0,3.0,2.0,8.0,4.2,NaN,NaN,,6
21,Domingue,Louis,ARI,1992-03-06,St-Hyacinthe,QC,CAN,CAN,75,210,...,113.230679,3.0,0.0,2.0,5.0,4.6,6.0,"Lower body, Lower body",76829.3,1
22,Driedger,Chris,OTT,1994-05-18,Winnipeg,MB,CAN,CAN,76,205,...,123.000000,NaN,NaN,NaN,NaN,-0.2,NaN,NaN,,8
23,Dubnyk,Devan,MIN,1986-05-04,Regina,SK,CAN,CAN,78,213,...,109.334753,8.0,6.0,8.0,22.0,13.1,NaN,NaN,,2
24,Elliott,Brian,CGY,1985-04-09,Newmarket,ON,CAN,CAN,74,209,...,108.444028,6.0,7.0,5.0,18.0,7.3,1.0,Illness,30487.8,1
25,Enroth,Jhonas,TOR,1988-06-25,Stockholm,NaN,SWE,SWE,70,175,...,112.377019,NaN,NaN,NaN,NaN,0.2,NaN,NaN,,8
26,Fleury,Marc-Andre,PIT,1984-11-28,Sorel,QC,CAN,CAN,74,180,...,117.360311,5.0,3.0,3.0,11.0,6.4,NaN,NaN,,2
27,Forsberg,Anton,CBJ,1992-11-27,Härnösand,NaN,SWE,SWE,75,192,...,110.611664,NaN,NaN,NaN,NaN,0.0,NaN,NaN,,8
28,Gibson,John,ANA,1993-07-14,Pittsburgh,PA,USA,USA,75,226,...,109.329402,7.0,8.0,2.0,17.0,10.3,13.0,Lowe body,364634,1
29,Gillies,Jon,CGY,1994-01-22,Concord,NH,USA,USA,78,223,...,109.000000,1.0,0.0,0.0,1.0,0.3,NaN,NaN,,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Mrazek,Petr,DET,1992-02-14,Ostrava,NaN,CZE,CZE,74,183,...,101.689696,3.0,4.0,6.0,13.0,6.5,NaN,NaN,,4
66,Murray,Matt,PIT,1994-05-25,Thunder Bay,ON,CAN,CAN,76,178,...,115.453033,2.0,5.0,2.0,9.0,10.3,8.0,"Hand, Lower body",61300.8,1
67,Nedeljkovic,Alex,CAR,1996-01-07,Parma,OH,USA,USA,72,198,...,102.170284,NaN,NaN,NaN,NaN,0.3,NaN,NaN,,11
68,Neuvirth,Michal,PHI,1988-03-23,Ústí nad Labem,NaN,CZE,CZE,73,209,...,114.444254,0.0,1.0,1.0,2.0,1.9,27.0,"Knee, Undisclosed",535061,2
69,Niemi,Antti,DAL,1983-08-29,Vantaa,NaN,FIN,FIN,74,215,...,120.208273,5.0,2.0,0.0,7.0,3.0,NaN,NaN,,6
70,Nilsson,Anders,BUF,1990-03-19,Lulea,NaN,SWE,SWE,78,229,...,115.654371,4.0,1.0,1.0,6.0,6.0,3.0,Undisclosed,36585.4,2
71,Pavelec,Ondrej,WPG,1987-08-31,Kladno,NaN,CZE,CZE,75,215,...,108.941980,0.0,2.0,1.0,3.0,0.7,24.0,"Lower body, Knee",1.14146e+06,2
72,Peters,Justin,ARI,1986-08-30,Blyth,ON,CAN,CAN,73,210,...,101.115987,NaN,NaN,NaN,NaN,0.3,NaN,NaN,,7
73,Pickard,Calvin,COL,1992-04-15,Moncton,NB,CAN,CAN,73,200,...,106.926059,3.0,4.0,8.0,15.0,7.1,NaN,NaN,,3
74,Price,Carey,MTL,1987-08-16,Anahim Lake,BC,CAN,CAN,75,226,...,111.371400,9.0,9.0,6.0,24.0,12.6,3.0,Flu,237805,0
75,Quick,Jonathan,LAK,1986-01-21,Milford,CT,USA,USA,73,218,...,114.141468,3.0,3.0,1.0,7.0,2.7,59.0,Lower body,4.17317e+06,1
76,Raanta,Antti,NYR,1989-05-12,Rauma,NaN,FIN,FIN,72,195,...,108.808739,4.0,4.0,1.0,9.0,5.4,5.0,Lower body,60975.6,5
77,Rask,Tuukka,BOS,1987-03-10,Savonlinna,NaN,FIN,FIN,75,176,...,109.563799,14.0,4.0,8.0,26.0,9.8,4.0,Lower body,341463,1
78,Reimer,James,FLA,1988-03-15,Morweena,MB,CAN,CAN,74,217,...,107.528948,3.0,5.0,5.0,13.0,8.1,3.0,Undisclosed,124390,1
79,Rinne,Pekka,NSH,1982-11-03,Kempele,NaN,FIN,FIN,77,217,...,111.598705,5.0,9.0,10.0,24.0,11.3,2.0,"Illness, Lower body",170732,1
80,Rittich,David,CGY,1992-08-19,Jihlava,NaN,CZE,CZE,75,202,...,108.000000,NaN,NaN,NaN,NaN,0.0,NaN,NaN,,15
81,Saros,Juuse,NSH,1995-04-19,Forssa,NaN,FIN,FIN,71,180,...,112.507813,4.0,1.0,5.0,10.0,4.4,NaN,NaN,,4
82,Schneider,Cory,NJD,1986-03-18,Marblehead,MA,USA,USA,75,205,...,99.791717,5.0,4.0,7.0,16.0,9.5,NaN,NaN,,2
83,Smith,Jeremy,COL,1989-04-13,Dearborn,MI,USA,USA,72,177,...,106.464392,0.0,0.0,1.0,1.0,0.8,NaN,NaN,,3
84,Smith,Mike,ARI,1982-03-22,Kingston,ON,CAN,CAN,76,215,...,115.348101,7.0,4.0,6.0,17.0,10.9,13.0,"Lower body, Illness",898374,0
85,Stalock,Alex,MIN,1987-07-28,St. Paul,MN,USA,USA,72,187,...,100.911002,0.0,0.0,1.0,1.0,0.5,NaN,NaN,,3
86,Stolarz,Anthony,PHI,1994-01-20,Edison,NJ,USA,USA,78,210,...,106.891203,1.0,1.0,1.0,3.0,1.4,NaN,NaN,,3
87,Subban,Malcolm,BOS,1993-12-21,Toronto,ON,CAN,CAN,74,200,...,107.843137,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,,7
88,Talbot,Cam,EDM,1987-07-05,Caledonia,ON,CAN,CAN,75,199,...,112.035398,11.0,8.0,2.0,21.0,14.0,NaN,NaN,,5
89,Tokarski,Dustin,ANA,1989-09-16,Watson,SK,CAN,CAN,72,205,...,91.993186,NaN,NaN,NaN,NaN,0.1,NaN,NaN,,11
90,Ullmark,Linus,BUF,1993-07-31,Lugnvik,NaN,SWE,SWE,76,221,...,100.113507,NaN,NaN,NaN,NaN,0.2,NaN,NaN,,8
91,Varlamov,Semyon,COL,1988-04-27,Samara,NaN,RUS,RUS,74,209,...,107.465344,3.0,3.0,1.0,7.0,3.1,50.0,"Upper body, Groin, Hip",3.59756e+06,2
92,Vasilevskiy,Andrei,TBL,1994-07-25,Tyumen,NaN,RUS,RUS,75,207,...,108.651016,4.0,8.0,2.0,14.0,9.3,NaN,NaN,,4
93,Ward,Cam,CAR,1984-02-29,Saskatoon,SK,CAN,CAN,73,185,...,108.609467,5.0,6.0,6.0,17.0,8.5,NaN,NaN,,2
94,Zatkoff,Jeff,LAK,1987-06-09,Detroit,MI,USA,USA,74,186,...,109.011628,NaN,NaN,NaN,NaN,0.4,11.0,Lower body,120732,5

### Q4) Matplotlib Question Plot in one figure and 2 side by side plots:
<br> </br>
#### A. Plot the histogram of the all the GAA of the NHL_Goalies DF  AND the goalies that played in more than 25 games with a GAA < 3.00, 
#### B. Label the Titles of the plots differently (*ie EntireSet + Subset*)
#### C. Change the color of one of the plots from the default

# Notes

1. convert your column of interest into a NumPY array (look up online for usage)
2. Review: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.hist.html

In [ ]:
#Answer 4 here: pleae comment

### Q5) GroupBy Question
##### 1. Subset the NHL_Goalies DataFrame where Injuries is not known <font color='red'>(Injuries=NaN)</font>; 
##### 2. Use a Merge with the GAA_  DF to produce a NEW DF (*called mergedDF*) 
###### *** USE A JOIN THAT PRESERVES ORDER AND USES THE INTERSECTION OF KEYS***
###### *** USE BOTH THE LEFT AND RIGHT INDEXES AS JOIN KEYS***
##### 3. From the mergedDF keep FirstName/LastName/Team/Cntry/ SV% /GA/GAA/ TOI (note one copy for any duplicate column)
##### 4. GroupBy country on mergedDF and aggregate The Means, Mins, and Maximum of the kept columns
#### 5. Create a dataframe of the <font color='red'>TOI </font>groupby object and write it to a comma seperated value file called ('TOI_2017.csv')

## Notes:

1. Review how to create selection criteria and how aggs/joins work from lecture notes;
2. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html
3. https://stackoverflow.com/questions/14734533/how-to-access-pandas-groupby-dataframe-by-key
4. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.get.html

In [ ]:
#Answer 5 here: please comments

# Q6) Write a function(s)  
## that subsets a dataframe by removing rows that are WITHIN the InterQuartile Region of a specified column
<br> </br>
### The function takes as input 
##### A: Pandas_Dataframe (For example use NHL_GoaliesDF)
##### B. Column name
### Add a condition that returns an error if the Column Name chosen is not:
##### A. Numeric Dtype
##### B. Does not exist in the Numeric Columns
### The output is a DataFrame that removes rows outside of the specified columns IQR
<br> </br>
<font color='red'>**You can use smaller helper functions **<font>
<br> </br>
See --> <href>=https://en.wikipedia.org/wiki/Interquartile_range</href>
#hint: There are several pandas subfunctions that can be useful

In [ ]:
#Answer Question 6 here

***For any questions regarding this assignment please email SAMSON: <br> </br><font color='green'>sjacob210@gmail.com ***</font>