# Pandas and Matplotlib Homework

In [1]:
#load the libraries using the normal convention
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
##prevent plotting errors
%matplotlib inline

/anaconda3/envs/itp_2018/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/envs/itp_2018/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
#Load our excel files of interest into pandas
NHL_Goalies = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheetname=0) 
GAA_ = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheetname='5vs5')

/anaconda3/envs/itp_2018/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)

#Appendix:
 1. DF = Pandas DataFrame
 2. NHL_Goalies DF = NHL_Goalies 
 3. GAA_ DF = GAA_

### Q1A) Create a new DF (*called NHL_Ones*) by:
#### Filtering the correct DF for Goalies that played 1 game <font color='red'> (GP = Games played)</font>

Notes: How would you find the 'GP' column in these files? Review from Pandas Lecture

In [7]:
# Answer 1A:

# find GP column in df, defining it as a variable here to use in next step
GP = NHL_Goalies.GP

# create new df, list players only when GP is equal to 1
NHL_Ones = NHL_Goalies[GP == 1]

# NHL_Ones
# NHL_Ones.GP

 ## Q1B) 
 #### A. Find the value of the minimum Salary for the entire dataset 
 #### B. Replace the missing values from the NHL_Ones DF with this
 #### C. Create a new DF after replacement by **adding** a column called  "Adjusted_Salary"
 #### D. I would like to only see the old "Salary" column and the "Adjusted Salary" column from the new Dataframe

#### Notes:
1. Note where the minimum Salary value is coming & where you are going to assign it to
2. Review notes from pandas **replacement**
3. Look up Numpy definition for null
4. Look up Pandas **Series** Naming 
5. Review concat function in Pandas
6. Review how to slice columns

In [8]:
# Answer 1B:
# A. Find the value of the minimum Salary for the entire dataset

Minimum_Salary = NHL_Goalies.Salary.min()

print('Minimum Salary: $',Minimum_Salary)

Minimum Salary: $ 575000.0

In [9]:
# Answer 1B:
# B. Replace the missing values from the NHL_Ones DF with this

NHL_Ones = NHL_Ones.replace('NaN', np.nan)
Adjusted_Salaries = NHL_Ones.Salary.replace(np.nan, Minimum_Salary)


print('Adjusted Salaries','\n', Adjusted_Salaries)

Adjusted Salaries
 1     575000.0
13    575000.0
14    575000.0
16    708750.0
22    780000.0
27    650000.0
29    925000.0
32    575000.0
42    575000.0
50    673334.0
67    575000.0
80    575000.0
87    832500.0
89    575000.0
90    892500.0
Name: Salary, dtype: float64

In [12]:
# Answer 1B: 
# C. Create a new DF after replacement by adding a column called "Adjusted_Salary"

NHL_Ones['Adjusted_Salary'] = Adjusted_Salaries

# NHL_Ones

In [13]:
# Answer 1B: 
# D. I would like to only see the old "Salary" column and the "Adjusted Salary" column from the new Dataframe

Salary_vs_Adjusted_Salary = pd.concat([NHL_Ones.Salary, NHL_Ones.Adjusted_Salary], axis=1)
Salary_vs_Adjusted_Salary

      Salary  Adjusted_Salary
1        NaN         575000.0
13       NaN         575000.0
14  575000.0         575000.0
16  708750.0         708750.0
22  780000.0         780000.0
27  650000.0         650000.0
29  925000.0         925000.0
32       NaN         575000.0
42  575000.0         575000.0
50  673334.0         673334.0
67       NaN         575000.0
80       NaN         575000.0
87  832500.0         832500.0
89       NaN         575000.0
90  892500.0         892500.0

### Q2) A. Subset the NHL goalies data to include Goalies that played in more than 25 games AND have a GAA lower than 3.00 and store the New DF as 'workhorse'

Notes: 
1. Review notes from Pandas Lecture on creating masks
2. Internet search for Multiple Boolean indexing on multiple columns in a Pandas DataFrame

In [21]:
# Answer 2:

GP = NHL_Goalies.GP
GAA = NHL_Goalies.GAA

Workhorse = NHL_Goalies[(GP > 25) & (GAA < 3.00)] 
 
Workhorse
# Workhorse_GP_GAA = pd.concat([Workhorse.GP, Workhorse.GAA], axis=1)
# Workhorse_GP_GAA

,Last Name,First Name,Team,DOB,Birth City,S/P,Cntry,Nat,Ht,Wt,...,Cap Hit,Pace,1st,2nd,3rd,Star,GPS,Ginj,Injuries,CHIP
0,Allen,Jake,STL,1990-08-07,Fredericton,NB,CAN,CAN,74,203,...,2350000.0,104.033662,9.0,7.0,6.0,22.0,9.8,NaN,NaN,
2,Andersen,Frederik,TOR,1989-10-02,Herning,NaN,DNK,DNK,76,230,...,5000000.0,118.931391,9.0,6.0,6.0,21.0,13.1,2.0,Upper body,121951
3,Anderson,Craig,OTT,1981-05-21,Park Ridge,IL,USA,USA,74,187,...,4200000.0,114.858819,8.0,2.0,5.0,15.0,9.2,2.0,Lower body,102439
5,Bernier,Jonathan,ANA,1988-08-07,Laval,QC,CAN,CAN,72,184,...,4150000.0,113.938340,5.0,0.0,2.0,7.0,6.0,3.0,Upper body,151829
9,Bishop,Ben,"TBL, LAK",1986-11-21,Denver,CO,USA,USA,79,216,...,5950000.0,108.466747,0.0,1.0,5.0,6.0,5.7,9.0,Lower body,653049
10,Bobrovsky,Sergei,CBJ,1988-09-20,Novokuznetsk,NaN,RUS,RUS,74,182,...,7425000.0,109.525950,17.0,6.0,6.0,29.0,14.9,2.0,Illness,181098
12,Budaj,Peter,"LAK, TBL",1982-09-18,Banská Bystrica,NaN,SVK,SVK,73,196,...,600000.0,108.110995,4.0,7.0,4.0,15.0,8.6,NaN,NaN,
15,Condon,Mike,"PIT, OTT",1990-04-27,Holliston,MA,USA,USA,74,197,...,575000.0,112.079733,9.0,1.0,4.0,14.0,6.8,NaN,NaN,
18,Crawford,Corey,CHI,1984-12-31,Montreal,QC,CAN,CAN,74,216,...,6000000.0,112.428393,8.0,5.0,0.0,13.0,11.0,11.0,"Appendectomy, Illness",804878
19,Darling,Scott,CHI,1988-12-22,Newport News,VA,USA,USA,78,232,...,587500.0,109.476386,5.0,5.0,5.0,15.0,6.2,5.0,Upper body,35823.2
23,Dubnyk,Devan,MIN,1986-05-04,Regina,SK,CAN,CAN,78,213,...,4333333.0,109.334753,8.0,6.0,8.0,22.0,13.1,NaN,NaN,
24,Elliott,Brian,CGY,1985-04-09,Newmarket,ON,CAN,CAN,74,209,...,2500000.0,108.444028,6.0,7.0,5.0,18.0,7.3,1.0,Illness,30487.8
28,Gibson,John,ANA,1993-07-14,Pittsburgh,PA,USA,USA,75,226,...,2300000.0,109.329402,7.0,8.0,2.0,17.0,10.3,13.0,Lowe body,364634
30,Greiss,Thomas,NYI,1986-01-29,Fussen,NaN,DEU,DEU,73,228,...,1500000.0,115.658454,2.0,6.0,6.0,14.0,8.6,NaN,NaN,
34,Halak,Jaroslav,NYI,1985-05-13,Bratislava,NaN,SVK,SVK,71,181,...,4500000.0,116.862004,4.0,1.0,1.0,6.0,5.4,NaN,NaN,
37,Hellebuyck,Connor,WPG,1993-05-19,Commerce,MI,USA,USA,76,207,...,667500.0,107.597892,7.0,1.0,2.0,10.0,8.1,NaN,NaN,
38,Holtby,Braden,WSH,1989-09-16,Lloydminster,SK,CAN,CAN,74,217,...,6100000.0,109.755899,11.0,8.0,7.0,26.0,12.3,NaN,NaN,
39,Howard,Jimmy,DET,1984-03-26,Syracuse,NY,USA,USA,73,218,...,5291667.0,104.516545,6.0,2.0,2.0,10.0,5.1,38.0,"Groin, Knee",2.45224e+06
40,Hutchinson,Michael,WPG,1990-03-02,Barrie,ON,CAN,CAN,75,202,...,1150000.0,104.430472,2.0,1.0,1.0,4.0,3.2,NaN,NaN,
41,Hutton,Carter,STL,1985-12-19,Thunder Bay,ON,CAN,CAN,73,195,...,1125000.0,104.040300,5.0,3.0,1.0,9.0,3.8,NaN,NaN,
43,Johnson,Chad,CGY,1986-06-10,Saskatoon,SK,CAN,CAN,75,196,...,1700000.0,105.771905,7.0,2.0,1.0,10.0,5.4,2.0,Lower body,41463.4
44,Jones,Martin,SJS,1990-01-10,North Vancouver,BC,CAN,CAN,76,190,...,3000000.0,114.352625,9.0,1.0,6.0,16.0,9.9,NaN,NaN,
46,Kinkaid,Keith,NJD,1989-07-04,Farmingville,NY,USA,USA,75,195,...,725000.0,105.522498,3.0,2.0,2.0,7.0,4.9,1.0,Knee,8841.46
51,Lehner,Robin,BUF,1991-07-24,Gothenburg,NaN,SWE,SWE,76,239,...,2225000.0,110.839435,3.0,5.0,5.0,13.0,12.9,7.0,"Illness, Hip, Flu, Upper body",189939
52,Lehtonen,Kari,DAL,1983-11-16,Helsinki,NaN,FIN,FIN,76,190,...,5900000.0,114.649922,5.0,3.0,3.0,11.0,7.1,NaN,NaN,
55,Lundqvist,Henrik,NYR,1982-03-02,Are,NaN,SWE,SWE,73,188,...,8500000.0,111.429541,14.0,2.0,1.0,17.0,9.1,8.0,"Flu, Hip",829268
56,Luongo,Roberto,FLA,1979-04-04,Montreal,QC,CAN,CAN,75,217,...,5333333.0,107.488861,3.0,5.0,3.0,11.0,7.4,21.0,"Undisclosed, Upper body, Lower body",1.36585e+06
57,Markstrom,Jacob,VAN,1990-01-31,Gävle,NaN,SWE,SWE,78,196,...,1550000.0,101.752570,3.0,0.0,4.0,7.0,3.8,21.0,Lower body,396951
59,Mason,Steve,PHI,1988-05-29,Oakville,ON,CAN,CAN,76,210,...,4100000.0,113.576291,3.0,6.0,6.0,15.0,8.2,1.0,Illness,50000
63,Miller,Ryan,VAN,1980-07-17,East Lansing,MI,USA,USA,74,168,...,6000000.0,106.144434,10.0,4.0,3.0,17.0,10.3,4.0,"Undisclosed, Flu, Ankle",292683
66,Murray,Matt,PIT,1994-05-25,Thunder Bay,ON,CAN,CAN,76,178,...,628333.0,115.453033,2.0,5.0,2.0,9.0,10.3,8.0,"Hand, Lower body",61300.8
68,Neuvirth,Michal,PHI,1988-03-23,Ústí nad Labem,NaN,CZE,CZE,73,209,...,1625000.0,114.444254,0.0,1.0,1.0,2.0,1.9,27.0,"Knee, Undisclosed",535061
70,Nilsson,Anders,BUF,1990-03-19,Lulea,NaN,SWE,SWE,78,229,...,1000000.0,115.654371,4.0,1.0,1.0,6.0,6.0,3.0,Undisclosed,36585.4
73,Pickard,Calvin,COL,1992-04-15,Moncton,NB,CAN,CAN,73,200,...,1000000.0,106.926059,3.0,4.0,8.0,15.0,7.1,NaN,NaN,
74,Price,Carey,MTL,1987-08-16,Anahim Lake,BC,CAN,CAN,75,226,...,6500000.0,111.371400,9.0,9.0,6.0,24.0,12.6,3.0,Flu,237805
76,Raanta,Antti,NYR,1989-05-12,Rauma,NaN,FIN,FIN,72,195,...,1000000.0,108.808739,4.0,4.0,1.0,9.0,5.4,5.0,Lower body,60975.6
77,Rask,Tuukka,BOS,1987-03-10,Savonlinna,NaN,FIN,FIN,75,176,...,7000000.0,109.563799,14.0,4.0,8.0,26.0,9.8,4.0,Lower body,341463
78,Reimer,James,FLA,1988-03-15,Morweena,MB,CAN,CAN,74,217,...,3400000.0,107.528948,3.0,5.0,5.0,13.0,8.1,3.0,Undisclosed,124390
79,Rinne,Pekka,NSH,1982-11-03,Kempele,NaN,FIN,FIN,77,217,...,7000000.0,111.598705,5.0,9.0,10.0,24.0,11.3,2.0,"Illness, Lower body",170732
82,Schneider,Cory,NJD,1986-03-18,Marblehead,MA,USA,USA,75,205,...,6000000.0,99.791717,5.0,4.0,7.0,16.0,9.5,NaN,NaN,
84,Smith,Mike,ARI,1982-03-22,Kingston,ON,CAN,CAN,76,215,...,5666667.0,115.348101,7.0,4.0,6.0,17.0,10.9,13.0,"Lower body, Illness",898374
88,Talbot,Cam,EDM,1987-07-05,Caledonia,ON,CAN,CAN,75,199,...,4166667.0,112.035398,11.0,8.0,2.0,21.0,14.0,NaN,NaN,
92,Vasilevskiy,Andrei,TBL,1994-07-25,Tyumen,NaN,RUS,RUS,75,207,...,925000.0,108.651016,4.0,8.0,2.0,14.0,9.3,NaN,NaN,
93,Ward,Cam,CAR,1984-02-29,Saskatoon,SK,CAN,CAN,73,185,...,3300000.0,108.609467,5.0,6.0,6.0,17.0,8.5,NaN,NaN,

### Q3. Create 2 python functions that: 
<br> </br>
#### A. Creates/*Returns* a new DataFrame that displays the number of missing values in every column. 
#### This new DataFrame has one new column named "Missing" with the sum of the missing values from the columns

### Notes 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
** One Proposed method:**
1. Create a pandas series object from the sum of the nulls in every column (review class notes)
2. Convert the series object to a DataFrame and pass the list of column names from the input DataFrame as the index. (read Pandas Help online)
3. During the conversion of the series object to a DataFrame pass a columns argument to create a name for the new Output DataFrame's Column.

### Expected Output:
<img src='Missing_cols_expectedoutput.png'>

In [ ]:
# Answer 3A: CODE HERE; Please comment each part

#### B. Creates a new *column* called 'missing_values' in the input DF that sums the missing values in each row.

### Notes: 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
Review the Column creation method in lecture and the axis arguments needed

### Expected Output:
<img src= 'missingrows_expectedoutput.png'>

In [ ]:
#Answer 3B here; Please comment each part

### Q4) Matplotlib Question Plot in one figure and 2 side by side plots:
<br> </br>
#### A. Plot the histogram of the all the GAA of the NHL_Goalies DF  AND the goalies that played in more than 25 games with a GAA < 3.00, 
#### B. Label the Titles of the plots differently (*ie EntireSet + Subset*)
#### C. Change the color of one of the plots from the default

# Notes

1. convert your column of interest into a NumPY array (look up online for usage)
2. Review: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.hist.html

In [ ]:
#Answer 4 here: pleae comment

### Q5) GroupBy Question
##### 1. Subset the NHL_Goalies DataFrame where Injuries is not known <font color='red'>(Injuries=NaN)</font>; 
##### 2. Use a Merge with the GAA_  DF to produce a NEW DF (*called mergedDF*) 
###### *** USE A JOIN THAT PRESERVES ORDER AND USES THE INTERSECTION OF KEYS***
###### *** USE BOTH THE LEFT AND RIGHT INDEXES AS JOIN KEYS***
##### 3. From the mergedDF keep FirstName/LastName/Team/Cntry/ SV% /GA/GAA/ TOI (note one copy for any duplicate column)
##### 4. GroupBy country on mergedDF and aggregate The Means, Mins, and Maximum of the kept columns
#### 5. Create a dataframe of the <font color='red'>TOI </font>groupby object and write it to a comma seperated value file called ('TOI_2017.csv')

## Notes:

1. Review how to create selection criteria and how aggs/joins work from lecture notes;
2. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html
3. https://stackoverflow.com/questions/14734533/how-to-access-pandas-groupby-dataframe-by-key
4. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.get.html

In [ ]:
#Answer 5 here: please comments

# Q6) Write a function(s)  
## that subsets a dataframe by removing rows that are WITHIN the InterQuartile Region of a specified column
<br> </br>
### The function takes as input 
##### A: Pandas_Dataframe (For example use NHL_GoaliesDF)
##### B. Column name
### Add a condition that returns an error if the Column Name chosen is not:
##### A. Numeric Dtype
##### B. Does not exist in the Numeric Columns
### The output is a DataFrame that removes rows outside of the specified columns IQR
<br> </br>
<font color='red'>**You can use smaller helper functions **<font>
<br> </br>
See --> <href>=https://en.wikipedia.org/wiki/Interquartile_range</href>
#hint: There are several pandas subfunctions that can be useful

In [ ]:
#Answer Question 6 here

***For any questions regarding this assignment please email SAMSON: <br> </br><font color='green'>sjacob210@gmail.com ***</font>